kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-alertmanager
  labels:
    app: prometheus
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: monitoring
    name: prometheus-alertmanager
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/k8s-volumes/prometheus-alertmanager"
