kind: PersistentVolume
apiVersion: v1
metadata:
  name: prometheus-server
  labels:
    app: prometheus
    type: local
spec:
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: demo
    name: prometheus-server
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/k8s-volumes/prometheus-server"
